image: python:3.7.2
pipelines:
  default:
    - step:
        script:
          - python --version
          - pip install -r requirements.txt
          - flake8 --exclude=venv* --statistics
          - pytest -v --cov=calculator